name: Feature Request
description: 새로운 기능을 제안합니다 / Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        기능 제안을 해주셔서 감사합니다. 제안하신 기능에 대해 자세히 알려주세요.
        Thank you for suggesting a feature. Please provide details about your proposal.

  - type: dropdown
    id: category
    attributes:
      label: 기능 카테고리 / Feature Category
      description: 어떤 영역의 기능인가요?
      options:
        - docker-tar (Docker image operations)
        - helm-local (Helm chart operations)
        - s3-share (S3 operations)
        - tar-fat32 (File splitting/merging)
        - New command / 새로운 명령어
        - Improvement / 기존 기능 개선
        - Other / 기타
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 해결하고자 하는 문제 / Problem Description
      description: 현재 어떤 불편함이나 문제가 있나요?
      placeholder: |
        현재 ... 을 할 때 ... 가 불편합니다.
        Currently when doing ..., it's inconvenient because ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결 방법 / Proposed Solution
      description: 어떤 기능이 추가되면 좋을까요?
      placeholder: |
        ... 기능이 추가되면 ... 를 할 수 있을 것 같습니다.
        If ... feature is added, it would enable ...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: 사용 예시 / Usage Example
      description: 제안하는 기능을 어떻게 사용할 것 같나요?
      render: shell
      placeholder: |
        # 예상 사용법:
        $ cli-onprem your-command --option value
        ...

  - type: textarea
    id: alternatives
    attributes:
      label: 대안 / Alternatives Considered
      description: 다른 방법을 고려해 보셨나요?
      placeholder: |
        현재는 ... 로 해결하고 있지만, ... 가 더 좋을 것 같습니다.
        Currently using ... but ... would be better because ...

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위 (선택) / Priority (Optional)
      description: 이 기능이 얼마나 시급한가요?
      options:
        - Critical / 매우 시급
        - High / 높음
        - Medium / 보통
        - Low / 낮음
        - Nice to have / 있으면 좋음

  - type: checkboxes
    id: contribution
    attributes:
      label: 기여 의향 / Contribution
      description: 이 기능을 직접 구현하실 의향이 있나요?
      options:
        - label: 이 기능을 구현하는 PR을 제출할 의향이 있습니다 / I am willing to submit a PR to implement this feature
        - label: 테스트와 피드백을 제공할 수 있습니다 / I can provide testing and feedback

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보 / Additional Context
      description: 다른 도움이 될 만한 정보가 있나요?
      placeholder: 관련 이슈, 참고 자료, 스크린샷 등
